kdt:
  environment: "Default"
spring:
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
  profiles:
    include:
      - secret
    active: default
#server:
#  error:
#    whitelabel:
#      enabled: false